### ISSUE TITLE
[EPIC] Add all stats

### ISSUE THREAD

**Issue by dylan-smith** [dylan-smith/BarbarianSim#25]
## Stats
- [x] #313
- [x] #314
- [x] #315
- [x] #316
- [x] #317

## Damage
- [x] #318
- [ ] #319
- [ ] #320
- [ ] #321
- [ ] #322
- [x] #323
- [x] #324
- [ ] Critical Strike Damage to Crowd Controlled
- [ ] Critical Strike Damage to Vulnerable
- [ ] #325
- [ ] Crit Chance Physical against Elites
- [ ] #326
- [ ] +X% Damage for 4 seconds after killing an Elite
- [ ] #327
- [ ] #328
- [x] #329
- [x] #330
- [ ] #331
- [x] #332
- [x] #333
- [ ] #334
- [ ] #335
- [ ] #336
- [ ] #337
- [ ] #338
- [ ] #339
- [ ] #340
- [ ] #341
- [x] #342
- [ ] #343
- [x] #404
- [ ] #344
- [x] #345
- [ ] #346
- [ ] Non-Physical Damage

## Damage Reduction
- [ ] X% Cold Resistance
- [ ] X% Damage Reduction
- [ ] X% Damage Reduction from Close Enemies
- [ ] X% Damage Reduction from Distant Enemies
- [ ] X% Damage Reduction from Enemies that are Bleeding
- [ ] X% Damage Reduction from Vulnerable Enemies
- [ ] X% Damage Reduction while Control Impaired
- [ ] X% Damage Reduction while Fortified
- [ ] X% Damage Reduction while Healthy
- [ ] +X% Damage Reduction while Injured
- [ ] Damage Taken over Time Reduction
- [ ] X% Dodge Chance
- [ ] X% Dodge Chance against Close Enemies
- [ ] X% Dodge chance against Distant Enemies
- [ ] X% Fire Resistance
- [ ] X% Lightning Resistance
- [ ] X% Poison Resistance
- [ ] X% Resistance to All Elements
- [ ] X% Shadow Resistance
- [ ] +X% Total Armor

## Skills
- [x] #347
- [ ] #348
- [ ] #349
- [ ] #350
- [ ] #351
- [ ] #352
- [x] #353
- [ ] #354
- [ ] #355
- [x] #356
- [ ] #357
- [ ] #358
- [ ] #359
- [ ] #360
- [ ] #361
- [ ] #362
- [ ] #363
- [x] #364
- [x] #365

## Other
- [ ] Attacks reduce evades cooldown by 0.8 second
- [ ] #380
- [ ] #366
- [ ] X% Control Impaired Duration Reduction
- [ ] #367
- [ ] #368
- [ ] Evade grants 50% Movement Speed for 1 second
- [ ] #379
- [x] #369
- [ ] #406
- [x] #378
- [ ] +X Life On Kill
- [ ] +X Life Regeneration while Not Damaged Recently
- [x] #370
- [ ] #371
- [ ] #372
- [ ] #377
- [ ] #373
- [ ] #374
- [ ] +X Max Evade Charges
- [x] #375
- [x] #376
- [x] #381
- [ ] +X% Movement Speed for 4 seconds after killing an Elite
- [ ] +X Potion Capacity
- [x] #382
- [ ] +X% Shrine Buff Duration
- [ ] X% Slow Duration Reduction
- [ ] +X Thorns
- [ ] While Injured, Your Potion also grants 20% Maximum Life as Barrier
- [ ] While Injured, your potion also grants 30% Movement Speed for 2 seconds
- [ ] While Injured, your potion also restores 20% resource
